global:
    scrape_interval: 10s
    evaluation_interval: 30s

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 10s
      static_configs:
        - targets: ['localhost:9090']

remote_write:
    - url: http://localhost:8000/write
      name: backup_write